
# Studyathons

## Upcoming 

### OHDSI UK 2025

- Elin antibiotics oral poster
- Marti OmopConstructor oral presentation and software demo

### OHDSI Africa 2025

- Eds high cost medicines oral presentation

### HDR-UK Conference 2025

- Eds high cost medicines oral presentation
- Cecilia HERON-UK onboarding

## Previous

### OHDSI Europe 2025

- **Elin Rowlands**, Cecilia Campanile, Hiba Junaid, Jennifer Lane, Usama Rahman, Ben Eaton, Xavier Griffin, Andy South, Ana Cavalcante, Duncan Cartner, Baptiste Briot Ribeyre, Steve Harris, Ofran Almossawi, Lydia Briggs, Daniel Key, Timothy Howcroft, Vishnu Chandrabalan, Peter S Hall, Mahéva Vallet, Marta Pasikowska, Nicola Symmers, Colin McLean, Spyro Nita, Daniel Dedman, Zara Cuccu, Stelios Theophanous, Danielle Newby, Daniel Prieto Alhambra, Marti Catala and Edward Burn. *Characterising the use of antibiotics commonly associated with antimicrobial resistance in UK primary and hospital care*. OHDSI Europe 2025 conference, 7th July 2025, Hasselt, Belgium. Oral presentation.

- **Cecilia Campanile**, Elin Rowlands, Hiba Junaid, Jennifer Lane, Usama Rahman, Ben Eaton, Xavier Griffin, Andy South, Ana Cavalcante, Duncan Cartner, Baptiste Briot Ribeyre, Steve Harris, Ofran Almossawi, Lydia Briggs, Daniel Key, Timothy Howcroft, Vishnu Chandrabalan, Peter S Hall, Mahéva Vallet, Marta Pasikowska, Nicola Symmers, Colin McLean, Spyro Nita, Daniel Dedman, Zara Cuccu, Stelios Theophanous, Danielle Newby, Daniel Prieto Alhambra,  Edward Burn and Marti Catala. *Characterisation of Data Sources in the HEalth data Real World Evidence OMOP Network (HERON UK)*. OHDSI Europe 2025 conference, 7th July 2025, Hasselt, Belgium. Poster presentation.

- **Alex Knight**, David Seymour, Uwaye Ideh, Cecilia Campanile, Elin Rowlands, Danielle Newby, Edward Burn, Martí Català and Daniel Prieto-Alhambra. *Establishing a Health Data RWE OMOP Network for the UK: HERON-UK*. OHDSI Europe 2025 conference, 7th July 2025, Hasselt, Belgium. Poster presentation.

- Andy South, Hiba Junaid, Jennifer Lane, Usama Rahman, Ben Eaton, Xavier Griffin, Ana Cavalcante, Steve Harris, Ofran Almossawi, Lydia Briggs, Daniel Key, Timothy Howcroft, Vishnu Chandrabalan, Peter S Hall, Mahéva Vallet, Marta Pasikowska, Nicola Symmers, Colin McLean, Spyro Nita, Daniel Dedman, Zara Cuccu, Stelios Theophanous,  Geoff Hall, Edward Bolton, Cecilia Campanile, Elin Rowlands, Danielle Newby, Daniel Prieto Alhambra, Edward Burn and **Marti Catala**. *Moving towards standard observation period settings for OMOP-based EHR data: results from the HERON-UK network*. OHDSI Europe 2025 conference, 7th July 2025, Hasselt, Belgium. Poster presentation.

- Cecilia software demo
- Eds high cost medicines poster





