project:
  type: website

date: today

website:
  title: "HERON-UK"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  repo-url: https://github.com/heron-uk/heron-uk
  repo-actions: [issue]
  page-footer:
    center: "Rendered on {{< meta date >}}"
  navbar:
    search: false
    left: 
      - text: "About"
        menu:
          - text: "About"
            href: about/about_heron_uk.qmd
          - text: "Funding"
            href: about/funding.qmd
          - text: "Organisational structure"
            href: about/organisational_structure.qmd
      - text: "Data network"
        menu:            
          - text: "Data partners"
            href: data_network/data_partners.qmd
          - text: "Data overview"
            href: data_network/data_overview.qmd 
      - text: "Joining the network"
        menu:
          - text: "How to join"
            href: join/how_to_join.qmd 
          - text: "Onboarding process"
            href: join/onboarding.qmd    
      - text: "Data conventions"
        menu:
          - text: "Introduction"
            href: data_conventions/introduction.qmd
          - text: "Observation period"
            href: data_conventions/observation_period.qmd
          - text: "Socioeconoic status"
            href: data_conventions/socioeconomic_status.qmd
          - text: "Ethnicity"
            href: data_conventions/ethnicity.qmd                     
      - text: "Network activities"
        menu:
          - text: "Studies"
            href: network_activities/study_overview.qmd
          - text: "Publications"
            href: network_activities/publications.qmd
          - text: "Presentations"
            href: network_activities/presentations.qmd
          - text: "Software"
            href: network_activities/software.qmd
format:
  html:
    toc: true
    theme: flatly
  