project:
  type: website

date: today

website:
  title: "HERON-UK"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  repo-url: https://github.com/heron-uk/heron-uk
  repo-actions: [issue]
  page-footer:
    center: "Rendered on {{< meta date >}}"
    left: "Copyright 2025, Oxinfer"
  navbar:
    search: false
    left: 
      - text: "Network activities"
        menu:
          - text: "Studies"
            href: network_activities/studies.qmd
          - text: "Studyathons"
            href: network_activities/studyathons.qmd
          - text: "Dissemination"
            href: network_activities/dissemination.qmd
      - text: "Onboarding"
        menu:
          - text: "Onboarding process"
            href: onboarding/index.qmd
          - text: "Conventions"
            href: onboarding/conventions.qmd
          - text: "Data partners"
            href: onboarding/data_partners.qmd
format:
  html:
    toc: true
    theme: flatly
  