on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Set up R and cache base packages
        uses: rstudio/shiny-workflows/setup-r-package@v1
        with:
          packages: |
            renv
            sessioninfo
            pak
          cache-version: v1

       - name: Install project-specific R dependencies
         shell: Rscript {0}
         run: |
           deps <- unique(renv::dependencies()$Package)
           message("Installing dependencies: ", paste(deps, collapse = ", "))
           pak::pak(deps, upgrade = FALSE)
        
       - name: Render and Publish
         uses: quarto-dev/quarto-actions/publish@v2
         with:
           target: gh-pages
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          