on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 

      - name: Install R
        uses: r-lib/actions/setup-r@v2
      
      # this will install the latest versions of packages being used explicitly
      # if some packages are in suggests please use library(gt) in a hide r 
      # code block so the package is installed
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: website
          
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Render Quarto website
        run: quarto render

      - name: Publish
        if: github.event_name != 'pull_request'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
          publish_dir: ./_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
